#!/usr/bin/env python3
"""Project canonical Overview and compact synthesis into public Hugo pages."""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

GENERATED_NOTICE = "<!-- Generated by scripts/prepare-overview-projections.py; do not edit manually. -->"
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")


@dataclass(frozen=True)
class ProjectionReport:
    synthesis_source: str
    source_count: int
    history_days: int
    changed_files: int


def _split_front_matter(text: str) -> tuple[dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError("Overview must start with YAML front matter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError("Overview front matter is unterminated") from exc
    metadata: dict[str, str] = {}
    for line in lines[1:end]:
        if not line or line.startswith(" ") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        metadata[key.strip()] = value
    return metadata, "\n".join(lines[end + 1 :])


def _overview_sections(text: str) -> tuple[dict[str, str], str, str, str]:
    metadata, body = _split_front_matter(text)
    patterns = {
        "overview": re.compile(r"(?m)^# Overview\s*$"),
        "synthesis": re.compile(r"(?m)^## Current Synthesis\s*$"),
        "questions": re.compile(r"(?m)^## Open Questions\s*$"),
    }
    matches = {name: list(pattern.finditer(body)) for name, pattern in patterns.items()}
    for name, found in matches.items():
        if len(found) != 1:
            raise ValueError(f"Overview must contain exactly one {name} heading")
    top, synthesis, questions = matches["overview"][0], matches["synthesis"][0], matches["questions"][0]
    if not (top.end() < synthesis.start() < questions.start()):
        raise ValueError("Overview headings are out of order")
    return (
        metadata,
        body[top.end() : synthesis.start()].strip(),
        body[synthesis.end() : questions.start()].strip(),
        body[questions.end() :].strip(),
    )


def _compact(root: Path, known_keys: set[str]) -> tuple[dict[str, object], str]:
    base = root / "wiki/_generated/synthesis"
    current = base / "current.md"
    manifest_path = base / "manifest.json"
    if current.is_symlink() or manifest_path.is_symlink() or not current.is_file() or not manifest_path.is_file():
        raise ValueError("compact synthesis current.md and manifest.json are required")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError("compact synthesis manifest is invalid") from exc
    if not isinstance(manifest, dict) or manifest.get("schema_version") != 1 or manifest.get("generated") is not True:
        raise ValueError("compact synthesis manifest has an unsupported schema")
    global_state = manifest.get("global")
    if not isinstance(global_state, dict):
        raise ValueError("compact synthesis manifest has no global state")
    actual_digest = hashlib.sha256(current.read_bytes()).hexdigest()
    if global_state.get("output_digest") != actual_digest:
        raise ValueError("compact synthesis digest differs from its manifest")
    text = current.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or not lines[0].startswith("<!-- Generated by ") or "synthesis;" not in lines[0]:
        raise ValueError("compact synthesis is missing its canonical generated marker")
    try:
        start = lines.index("---", 1)
        end = lines.index("---", start + 1)
    except ValueError as exc:
        raise ValueError("compact synthesis front matter is invalid") from exc
    metadata: dict[str, object] = {}
    for line in lines[start + 1 : end]:
        if ":" not in line:
            continue
        key, raw = line.split(":", 1)
        value = raw.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = json.loads(value)
        if value in {"true", "false"}:
            metadata[key.strip()] = value == "true"
        elif re.fullmatch(r"0|[1-9][0-9]*", str(value)):
            metadata[key.strip()] = int(value)
        else:
            metadata[key.strip()] = value
    required = {"synthesis_source", "last_updated", "as_of_overview_commit", "summary", "source_count", "topic_count"}
    if not required.issubset(metadata):
        raise ValueError("compact synthesis metadata is incomplete")
    if metadata["synthesis_source"] != "compact":
        raise ValueError("compact synthesis source marker is invalid")
    try:
        dt.date.fromisoformat(str(metadata["last_updated"]))
    except ValueError as exc:
        raise ValueError("compact synthesis date is invalid") from exc
    corpus = global_state.get("corpus")
    if not isinstance(corpus, dict) or corpus.get("source_count") != metadata["source_count"]:
        raise ValueError("compact synthesis source count differs from its manifest")
    topics = manifest.get("topics")
    if not isinstance(topics, dict) or len(topics) != metadata["topic_count"]:
        raise ValueError("compact synthesis topic count differs from its manifest")
    body = "\n".join(lines[end + 1 :]).strip()
    if len(re.findall(r"(?m)^# Current Synthesis\s*$", body)) != 1:
        raise ValueError("compact synthesis must contain one Current Synthesis heading")
    missing = sorted(set(WIKILINK_RE.findall(body)) - known_keys)
    if missing:
        raise ValueError(f"compact synthesis has missing Wiki targets: {', '.join(missing)}")
    return metadata, body


def _page(lines: list[str], body: str) -> bytes:
    return ("\n".join(["---", *lines, "---", "", body.strip(), "", GENERATED_NOTICE]).rstrip() + "\n").encode("utf-8")


def _history_events(root: Path, canonical_text: str, intro: str, updated: str) -> list[tuple[str, str, str]]:
    """Return deterministic visible overview events; first sync is an explicit baseline."""
    path = "wiki/overview.md"
    result = subprocess.run(
        ["git", "-C", str(root), "log", "--reverse", "--format=%H%x09%aI", "--", path],
        text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    events: list[tuple[str, str, str]] = []
    seen_bodies: set[str] = set()
    if result.returncode == 0:
        for line in result.stdout.splitlines():
            if "\t" not in line:
                continue
            commit, authored = line.split("\t", 1)
            shown = subprocess.run(
                ["git", "-C", str(root), "show", f"{commit}:{path}"],
                text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            )
            if shown.returncode != 0:
                continue
            try:
                metadata, historical_intro, _synthesis, _questions = _overview_sections(shown.stdout)
            except ValueError:
                continue
            if historical_intro and historical_intro not in seen_bodies:
                day = metadata.get("last_updated") or authored[:10]
                events.append((day, commit, historical_intro))
                seen_bodies.add(historical_intro)
    if intro and intro not in seen_bodies:
        events.append((updated, "first-sync", intro))
    if not events:
        events.append((updated, "first-sync", "First synchronized canonical overview."))
    events.sort(key=lambda item: (item[0], item[1]), reverse=True)
    return events


def _expected(root: Path) -> tuple[dict[Path, bytes], ProjectionReport]:
    canonical = root / "wiki/overview.md"
    if canonical.is_symlink() or not canonical.is_file():
        raise ValueError("canonical wiki/overview.md is required")
    canonical_text = canonical.read_text(encoding="utf-8")
    overview_meta, intro, _legacy_synthesis, questions = _overview_sections(canonical_text)
    updated = overview_meta.get("last_updated", "")
    try:
        dt.date.fromisoformat(updated)
    except ValueError as exc:
        raise ValueError("Overview last_updated is invalid") from exc
    known_keys = {
        path.stem
        for section in ("concepts", "entities", "sources")
        for path in (root / "wiki" / section).glob("*.md")
    }
    compact_meta, compact_body = _compact(root, known_keys)
    current_lines = [
        'title: "Current Synthesis"', 'type: "wiki"', 'url: "/wiki/current-synthesis/"',
        'outputs: ["html"]', "wiki_projection: true", 'synthesis_source: "compact"',
        f"last_updated: {json.dumps(str(compact_meta['last_updated']))}",
        f"as_of_overview_commit: {json.dumps(str(compact_meta['as_of_overview_commit']))}",
        f"summary: {json.dumps(str(compact_meta['summary']), ensure_ascii=False)}",
        f"source_count: {compact_meta['source_count']}", f"topic_count: {compact_meta['topic_count']}",
    ]
    question_body = "# Open Questions\n\n" + questions
    question_lines = [
        'title: "Open Questions"', 'type: "wiki"', 'url: "/wiki/open-questions/"',
        'outputs: ["html"]', "wiki_projection: true",
    ]
    events = _history_events(root, canonical_text, intro, updated)
    history_lines = [
        'title: "Update History"', 'type: "wiki"', 'url: "/wiki/updates/"',
        'outputs: ["html"]', "wiki_projection: true", f"history_days: {len({event[0] for event in events})}",
    ]
    grouped: dict[str, list[tuple[str, str]]] = {}
    for day, commit, body in events:
        grouped.setdefault(day, []).append((commit, body))
    history_body = ["# Update History", ""]
    for day in sorted(grouped, reverse=True):
        history_body.extend([f"## {day}", ""])
        for commit, body in grouped[day]:
            label = "First synchronized canonical overview" if commit == "first-sync" else f"Canonical overview revision `{commit[:12]}`"
            history_body.extend([f"### {label}", "", body, ""])
    output = root / ".generated/wiki-projections"
    expected = {
        output / "_index.md": _page([
            'title: "Internal Wiki Projections"',
            'type: "wiki"',
            "build:",
            "  render: never",
            "  list: never",
        ], ""),
        output / "current-synthesis.md": _page(current_lines, compact_body),
        output / "open-questions.md": _page(question_lines, question_body),
        output / "update-history/_index.md": _page(history_lines, "\n".join(history_body)),
    }
    return expected, ProjectionReport("compact", int(compact_meta["source_count"]), len(grouped), 0)


def _safe(path: Path, root: Path) -> None:
    output = (root / ".generated/wiki-projections").resolve()
    try:
        (path.parent.resolve() / path.name).relative_to(output)
    except ValueError as exc:
        raise ValueError(f"overview projection escapes owned root: {path}") from exc
    current = root.resolve()
    for part in path.relative_to(root).parts[:-1]:
        current /= part
        if current.exists() and current.is_symlink():
            raise ValueError(f"overview projection ancestor is a symlink: {current}")


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def project(root: Path | str, check: bool = False) -> ProjectionReport:
    root = Path(root).resolve()
    canonical = root / "wiki/overview.md"
    before = hashlib.sha256(canonical.read_bytes()).hexdigest()
    expected, report = _expected(root)
    output = root / ".generated/wiki-projections"
    actual = {path for path in output.rglob("*") if path.is_file()} if output.exists() else set()
    stale = sorted(actual - set(expected))
    drifted = sorted(path for path, data in expected.items() if not path.is_file() or path.read_bytes() != data)
    if check:
        if stale:
            raise ValueError(f"stale overview projection: {stale[0].relative_to(root)}")
        if drifted:
            raise ValueError(f"overview projection differs: {drifted[0].relative_to(root)}")
        return report
    for path in drifted:
        _safe(path, root)
        if path.exists() and GENERATED_NOTICE not in path.read_text(encoding="utf-8", errors="replace"):
            raise ValueError(f"unowned overview projection collision: {path.relative_to(root)}")
        _atomic_write(path, expected[path])
    for path in stale:
        _safe(path, root)
        if GENERATED_NOTICE not in path.read_text(encoding="utf-8", errors="replace"):
            raise ValueError(f"unowned stale overview projection: {path.relative_to(root)}")
        path.unlink()
    for directory in sorted((path for path in output.rglob("*") if path.is_dir()), reverse=True) if output.exists() else []:
        try:
            directory.rmdir()
        except OSError:
            pass
    if hashlib.sha256(canonical.read_bytes()).hexdigest() != before:
        raise RuntimeError("canonical Overview changed during projection")
    return ProjectionReport(report.synthesis_source, report.source_count, report.history_days, len(drifted) + len(stale))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args(argv)
    try:
        report = project(args.root, check=args.check)
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"Overview projection failed: {exc}", file=sys.stderr)
        return 1
    print(f"Overview projections: days={report.history_days}, synthesis={report.synthesis_source}, source_count={report.source_count}, changed_files={report.changed_files}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
