#!/usr/bin/env python3
"""Derive Hugo-ready Personal Wiki content from canonical producer mirrors."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import struct
import sys
import tempfile
import unicodedata
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

GENERATED_NOTICE = "<!-- Generated by scripts/prepare-wiki-content.py; do not edit manually. -->"
GENERATED_JSON_KEY = "_generated_by"
GENERATOR_ID = "scripts/prepare-wiki-content.py"
PUBLIC_SECTIONS = ("concepts", "entities", "sources")
ALPHABETICAL_SECTIONS = ("concepts", "entities")
ALPHABETICAL_BUCKETS = ("0-9", *(chr(code) for code in range(ord("a"), ord("z") + 1)))
LINK_RE = re.compile(r"\[\[([^\]\n]+)\]\]")
KEY_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]*")
ASSET_NAME_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
ALLOWED_IMAGE_SUFFIXES = {".gif", ".jpeg", ".jpg", ".png", ".webp"}
MAX_IMAGE_BYTES = 32 * 1024 * 1024
MAX_IMAGE_DIMENSION = 20_000


@dataclass(frozen=True)
class WikiPage:
    key: str
    title: str
    section: str
    path: Path
    metadata: dict[str, object]

    @property
    def url(self) -> str:
        return f"/wiki/{self.section}/{self.key.casefold()}/"


@dataclass(frozen=True)
class PrepareReport:
    concepts: int
    entities: int
    sources: int
    references: int
    generated_files: int
    changed_files: int


def split_front_matter(text: str) -> tuple[list[str], str]:
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError("canonical Markdown must start with YAML front matter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError("canonical Markdown has unterminated front matter") from exc
    return lines[1:end], "\n".join(lines[end + 1 :])


def _scalar(raw: str) -> object:
    value = raw.strip()
    if not value:
        return ""
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_scalar(part) for part in inner.split(",")]
    if len(value) >= 2 and value[0] == value[-1] == '"':
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as exc:
            raise ValueError("invalid quoted front-matter scalar") from exc
        if not isinstance(parsed, str):
            raise ValueError("quoted front-matter scalar is not text")
        return parsed
    if len(value) >= 2 and value[0] == value[-1] == "'":
        return value[1:-1]
    if value in {"true", "false"}:
        return value == "true"
    if re.fullmatch(r"-?[0-9]+", value):
        return int(value)
    return value


def parse_front_matter(path: Path) -> tuple[dict[str, object], str]:
    lines, body = split_front_matter(path.read_text(encoding="utf-8"))
    metadata: dict[str, object] = {}
    index = 0
    while index < len(lines):
        line = lines[index]
        if not line or line.lstrip().startswith("#"):
            index += 1
            continue
        if line.startswith((" ", "\t")) or ":" not in line:
            raise ValueError(f"{path}: unsupported front matter at line {index + 2}")
        key, raw = line.split(":", 1)
        key = key.strip()
        if key in metadata:
            raise ValueError(f"{path}: duplicate front-matter key {key}")
        if raw.strip():
            metadata[key] = _scalar(raw)
            index += 1
            continue
        values: list[object] = []
        index += 1
        while index < len(lines) and lines[index].startswith("  - "):
            values.append(_scalar(lines[index][4:]))
            index += 1
        metadata[key] = values
    return metadata, body


def _require_regular_tree(root: Path, label: str) -> None:
    if root.is_symlink() or not root.is_dir():
        raise ValueError(f"{label} must be a regular directory")
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"{label} contains a symbolic link: {path.relative_to(root)}")
        if not path.is_dir() and not path.is_file():
            raise ValueError(f"{label} contains a special node: {path.relative_to(root)}")


def _validate_key(key: str, label: str) -> None:
    if not KEY_RE.fullmatch(key):
        raise ValueError(f"invalid {label}: {key!r}")


def discover_pages(root: Path) -> list[WikiPage]:
    wiki = root / "wiki"
    _require_regular_tree(wiki, "canonical wiki")
    pages: list[WikiPage] = []
    for section in PUBLIC_SECTIONS:
        directory = wiki / section
        if not directory.is_dir():
            raise ValueError(f"missing canonical section: wiki/{section}")
        for path in sorted(directory.glob("*.md")):
            key = path.stem
            _validate_key(key, f"{section} key")
            metadata, _ = parse_front_matter(path)
            expected_type = {"concepts": "concept", "entities": "entity", "sources": "source"}[section]
            if metadata.get("type") != expected_type:
                raise ValueError(f"{path}: type does not match section")
            title = metadata.get("title")
            if not isinstance(title, str) or not title.strip():
                raise ValueError(f"{path}: missing title")
            pages.append(WikiPage(key, title.strip(), section, path, metadata))
    _validate_identities(pages)
    return pages


def _validate_identities(pages: list[WikiPage]) -> None:
    exact: dict[str, WikiPage] = {}
    paths: dict[str, WikiPage] = {}
    routes: dict[str, WikiPage] = {}
    for page in pages:
        if page.key in exact:
            raise ValueError(f"duplicate canonical Wiki key: {page.key}")
        exact[page.key] = page
        folded_path = f"wiki/{page.section}/{page.path.name}".casefold()
        if folded_path in paths:
            raise ValueError(f"case-folded canonical path collision: {page.path.name}")
        paths[folded_path] = page
        route = page.url.casefold()
        if route in routes:
            raise ValueError(f"public Wiki route collision: {page.url}")
        routes[route] = page


def _wikilink_target(raw: str) -> str:
    return raw.split("|", 1)[0].split("#", 1)[0].strip()


def make_link_data(pages: list[WikiPage], root: Path) -> tuple[dict[str, object], int]:
    by_key = {page.key: page for page in pages}
    references = 0
    missing: dict[str, list[str]] = defaultdict(list)
    for path in sorted((root / "wiki").rglob("*.md")):
        if "_generated" in path.parts or path.name in {"index.md", "log.md"} or path == root / "wiki/overview.md":
            continue
        text = path.read_text(encoding="utf-8")
        for match in LINK_RE.finditer(text):
            references += 1
            target = _wikilink_target(match.group(1))
            if target not in by_key:
                missing[target].append(path.relative_to(root).as_posix())
    if missing:
        summary = ", ".join(f"{key} ({len(paths)})" for key, paths in sorted(missing.items()))
        raise ValueError(f"missing Wiki targets: {summary}")
    payload = {
        GENERATED_JSON_KEY: GENERATOR_ID,
        **{
            page.key: {"section": page.section, "title": page.title, "url": page.url}
            for page in sorted(pages, key=lambda item: item.key)
        },
    }
    return payload, references


def _image_dimensions(data: bytes, suffix: str) -> tuple[int, int]:
    if suffix == ".png":
        if len(data) < 24 or data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
            raise ValueError("invalid PNG encoding")
        return struct.unpack(">II", data[16:24])
    if suffix == ".gif":
        if len(data) < 10 or data[:6] not in {b"GIF87a", b"GIF89a"}:
            raise ValueError("invalid GIF encoding")
        return struct.unpack("<HH", data[6:10])
    if suffix in {".jpg", ".jpeg"}:
        if len(data) < 4 or data[:2] != b"\xff\xd8" or data[-2:] != b"\xff\xd9":
            raise ValueError("invalid JPEG encoding")
        offset = 2
        while offset + 4 <= len(data):
            if data[offset] != 0xFF:
                offset += 1
                continue
            marker = data[offset + 1]
            offset += 2
            if marker in {0xD8, 0xD9} or 0xD0 <= marker <= 0xD7:
                continue
            if offset + 2 > len(data):
                break
            length = int.from_bytes(data[offset : offset + 2], "big")
            if length < 2 or offset + length > len(data):
                break
            if marker in {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}:
                if length < 7:
                    break
                return int.from_bytes(data[offset + 3 : offset + 5], "big"), int.from_bytes(data[offset + 5 : offset + 7], "big")
            offset += length
        raise ValueError("JPEG dimensions are missing")
    if suffix == ".webp":
        if len(data) < 30 or data[:4] != b"RIFF" or data[8:12] != b"WEBP":
            raise ValueError("invalid WebP encoding")
        kind = data[12:16]
        if kind == b"VP8X":
            return 1 + int.from_bytes(data[24:27], "little"), 1 + int.from_bytes(data[27:30], "little")
        raise ValueError("unsupported WebP encoding")
    raise ValueError("unsupported image format")


def load_image_sidecars(root: Path, sources: list[WikiPage]) -> dict[str, list[tuple[str, str, bytes]]]:
    assets_root = root / "wiki-assets"
    _require_regular_tree(assets_root, "canonical wiki assets")
    source_keys = {page.key for page in sources}
    actual_directories = {path.name for path in assets_root.iterdir() if path.is_dir()}
    extra = sorted(actual_directories - source_keys)
    if extra:
        raise ValueError(f"image sidecar has no canonical source: {extra[0]}")
    result: dict[str, list[tuple[str, str, bytes]]] = {}
    for key in sorted(actual_directories):
        directory = assets_root / key
        manifest_path = directory / "manifest.json"
        if not manifest_path.is_file() or manifest_path.is_symlink():
            raise ValueError(f"missing image manifest for source {key}")
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid image manifest for source {key}") from exc
        if not isinstance(manifest, dict) or set(manifest) != {"version", "source_key", "images"}:
            raise ValueError(f"invalid image manifest schema for source {key}")
        if manifest["version"] != 1 or manifest["source_key"] != key or not isinstance(manifest["images"], list):
            raise ValueError(f"invalid image manifest identity for source {key}")
        images: list[tuple[str, str, bytes]] = []
        names: set[str] = set()
        for record in manifest["images"]:
            if not isinstance(record, dict) or set(record) != {"file", "alt"}:
                raise ValueError(f"invalid image record for source {key}")
            name, alt = record["file"], record["alt"]
            if not isinstance(name, str) or not ASSET_NAME_RE.fullmatch(name) or PurePosixPath(name).name != name:
                raise ValueError(f"invalid image filename for source {key}")
            if name.casefold() in {item.casefold() for item in names}:
                raise ValueError(f"duplicate image filename for source {key}: {name}")
            if not isinstance(alt, str) or not alt.strip() or any(char in alt for char in "\r\n\x00"):
                raise ValueError(f"invalid image alt text for source {key}: {name}")
            suffix = Path(name).suffix.casefold()
            if suffix not in ALLOWED_IMAGE_SUFFIXES:
                raise ValueError(f"unsupported image format for source {key}: {name}")
            path = directory / name
            if path.is_symlink() or not path.is_file():
                raise ValueError(f"missing image for source {key}: {name}")
            data = path.read_bytes()
            if not data or len(data) > MAX_IMAGE_BYTES:
                raise ValueError(f"invalid image size for source {key}: {name}")
            width, height = _image_dimensions(data, suffix)
            if not (1 <= width <= MAX_IMAGE_DIMENSION and 1 <= height <= MAX_IMAGE_DIMENSION):
                raise ValueError(f"invalid image dimensions for source {key}: {name}")
            names.add(name)
            images.append((name, alt.strip(), data))
        extras = sorted(path.name for path in directory.iterdir() if path.is_file() and path.name != "manifest.json" and path.name not in names)
        if extras:
            raise ValueError(f"unlisted image for source {key}: {extras[0]}")
        result[key] = images
    return result


def _bucket(key: str) -> str:
    for char in key:
        if char.isdigit():
            return "0-9"
        if char.isascii() and char.isalpha():
            return char.lower()
        if char.isalpha():
            normalized = unicodedata.normalize("NFKD", char)
            for candidate in normalized:
                if candidate.isascii() and candidate.isalpha():
                    return candidate.lower()
    raise ValueError(f"canonical Wiki key has no supported letter or digit: {key!r}")


def _front_matter(lines: list[str], body: str = "") -> bytes:
    text = "\n".join(["---", *lines, "---", "", body.rstrip(), GENERATED_NOTICE]).replace("\n\n\n", "\n\n")
    return (text.rstrip() + "\n").encode("utf-8")


def _wiki_index() -> bytes:
    return _front_matter([
        'title: "Wiki"', 'type: "wiki"', 'description: "Personal Wiki knowledge collections"',
        'outputs: ["html"]', "cascade:", '  outputs: ["html"]',
    ])


def _alphabetical_index(section: str, bucket: str, pages: list[WikiPage], total: int, landing: bool = False) -> bytes:
    title = section.title() if landing else f"{section.title()} — {bucket.upper()}"
    lines = [
        f"title: {json.dumps(title, ensure_ascii=False)}", 'type: "wiki"',
        f"description: {json.dumps(f'{section.title()} beginning with {bucket.upper()}', ensure_ascii=False)}",
        'outputs: ["html"]', "wiki_alphabetical: true", f"wiki_section: {json.dumps(section)}",
        f"wiki_letter: {json.dumps(bucket)}", f"wiki_total_pages: {total}",
    ]
    if pages:
        lines.append("wiki_pages:")
        for page in sorted(pages, key=lambda item: (item.title.casefold(), item.key.casefold())):
            lines.extend([
                f"  - key: {json.dumps(page.key, ensure_ascii=False)}",
                f"    title: {json.dumps(page.title, ensure_ascii=False)}",
                f"    url: {json.dumps(page.url)}",
            ])
    else:
        lines.append("wiki_pages: []")
    return _front_matter(lines)


def _stats(pages: list[WikiPage], references: int) -> bytes:
    counts = {section: sum(page.section == section for page in pages) for section in PUBLIC_SECTIONS}
    body = "\n".join([
        "# Wiki Stats", "", f"- Concepts: {counts['concepts']}", f"- Entities: {counts['entities']}",
        f"- Source notes: {counts['sources']}", f"- Wiki-link references: {references}",
    ])
    return _front_matter(['title: "Wiki Stats"', 'type: "wiki"', 'url: "/wiki/stats/"', 'outputs: ["html"]'], body)


def _source_projection(page: WikiPage, images: list[tuple[str, str, bytes]]) -> bytes:
    source = page.path.read_text(encoding="utf-8").rstrip()
    if images:
        source += "\n\n## Images\n\n" + "\n\n".join(f"![{alt}]({name})" for name, alt, _ in images)
    return (source + "\n\n" + GENERATED_NOTICE + "\n").encode("utf-8")


def _knowledge_signals(pages: list[WikiPage]) -> dict[str, object]:
    by_key = {page.key: page for page in pages}
    payload: dict[str, object] = {GENERATED_JSON_KEY: GENERATOR_ID, "pages": {}}
    records: dict[str, object] = payload["pages"]  # type: ignore[assignment]
    for page in sorted(pages, key=lambda item: item.key):
        if page.section not in {"concepts", "entities"} or page.metadata.get("knowledge_schema") != "synthesis-v1":
            continue
        sources = page.metadata.get("sources")
        if not isinstance(sources, list) or not sources or not all(isinstance(key, str) for key in sources):
            raise ValueError(f"{page.path}: synthesis-v1 sources must be a non-empty list")
        source_records: list[dict[str, str]] = []
        for source_key in sources:
            source = by_key.get(source_key)
            if source is None or source.section != "sources":
                raise ValueError(f"{page.path}: unknown source key {source_key}")
            source_records.append({"key": source.key, "title": source.title, "url": source.url})
        updated = page.metadata.get("last_updated")
        if not isinstance(updated, str) or not re.fullmatch(r"[0-9]{4}-[0-9]{2}-[0-9]{2}", updated):
            raise ValueError(f"{page.path}: invalid last_updated")
        records[page.key] = {
            "knowledge_schema": "synthesis-v1", "updated": updated,
            "source_note_count": len(dict.fromkeys(sources)), "sources": source_records,
        }
    return payload


def _expected(root: Path) -> tuple[dict[Path, bytes], PrepareReport]:
    pages = discover_pages(root)
    by_section = {section: [page for page in pages if page.section == section] for section in PUBLIC_SECTIONS}
    links, references = make_link_data(pages, root)
    sidecars = load_image_sidecars(root, by_section["sources"])
    generated = root / ".generated"
    expected: dict[Path, bytes] = {
        generated / "wiki/_index.md": _wiki_index(),
        generated / "wiki/stats.md": _stats(pages, references),
        generated / "data/wiki_links.json": (json.dumps(links, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode(),
        generated / "data/wiki_knowledge_signals.json": (json.dumps(_knowledge_signals(pages), ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode(),
    }
    for page in pages:
        if page.section == "sources":
            bundle = generated / "wiki/sources" / page.key
            images = sidecars.get(page.key, [])
            expected[bundle / "index.md"] = _source_projection(page, images)
            for name, _alt, data in images:
                expected[bundle / name] = data
        else:
            expected[generated / "wiki" / page.section / page.path.name] = page.path.read_bytes()
    for section in ALPHABETICAL_SECTIONS:
        groups = {bucket: [] for bucket in ALPHABETICAL_BUCKETS}
        for page in by_section[section]:
            groups[_bucket(page.key)].append(page)
        total = len(by_section[section])
        expected[generated / "wiki" / section / "_index.md"] = _alphabetical_index(
            section, "a", by_section[section], total, landing=True
        )
        expected[generated / "wiki" / section / "by-letter/_index.md"] = _alphabetical_index(section, "a", groups["a"], total)
        for bucket in ALPHABETICAL_BUCKETS:
            expected[generated / "wiki" / section / "by-letter" / bucket / "_index.md"] = _alphabetical_index(section, bucket, groups[bucket], total)
    expected[generated / "wiki/sources/_index.md"] = _front_matter([
        'title: "Sources"', 'type: "wiki"', 'description: "Canonical source notes"', 'outputs: ["html"]'
    ])
    manifest_payload = {
        GENERATED_JSON_KEY: GENERATOR_ID,
        "version": 1,
        "files": {
            path.relative_to(generated).as_posix(): hashlib.sha256(data).hexdigest()
            for path, data in sorted(expected.items(), key=lambda item: item[0].as_posix())
        },
    }
    expected[generated / "data/prepare-wiki-manifest.json"] = (
        json.dumps(manifest_payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    report = PrepareReport(
        concepts=len(by_section["concepts"]), entities=len(by_section["entities"]), sources=len(by_section["sources"]),
        references=references, generated_files=len(expected), changed_files=0,
    )
    return expected, report


def _load_previous_manifest(root: Path) -> dict[str, str]:
    path = root / ".generated/data/prepare-wiki-manifest.json"
    if path.is_symlink() or not path.is_file():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return {}
    files = payload.get("files") if isinstance(payload, dict) else None
    if payload.get(GENERATED_JSON_KEY) != GENERATOR_ID or not isinstance(files, dict):
        return {}
    return {key: value for key, value in files.items() if isinstance(key, str) and isinstance(value, str)}


def _is_owned(path: Path, root: Path, previous_manifest: dict[str, str]) -> bool:
    generated = root / ".generated"
    try:
        relative = path.relative_to(generated).as_posix()
    except ValueError:
        return False
    expected_digest = previous_manifest.get(relative)
    if expected_digest and path.is_file() and hashlib.sha256(path.read_bytes()).hexdigest() == expected_digest:
        return True
    if path.suffix.casefold() == ".md":
        try:
            return GENERATED_NOTICE in path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            return False
    if path.suffix.casefold() == ".json":
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            return False
        return isinstance(data, dict) and data.get(GENERATED_JSON_KEY) == GENERATOR_ID
    return True


def _safe_output(path: Path, root: Path) -> None:
    generated = (root / ".generated").resolve()
    lexical = path.parent.resolve() / path.name
    try:
        lexical.relative_to(generated)
    except ValueError as exc:
        raise ValueError(f"generated output escapes owned root: {path}") from exc
    current = root.resolve()
    for part in path.relative_to(root).parts[:-1]:
        current /= part
        if current.exists() and current.is_symlink():
            raise ValueError(f"generated output ancestor is a symlink: {current}")


def _owned_roots(root: Path) -> tuple[Path, ...]:
    return root / ".generated/wiki", root / ".generated/data"


def _actual_files(root: Path) -> set[Path]:
    return {path for directory in _owned_roots(root) if directory.exists() for path in directory.rglob("*") if path.is_file()}


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass


def prepare(root: Path | str, check: bool = False) -> PrepareReport:
    root = Path(root).resolve()
    previous_manifest = _load_previous_manifest(root)
    canonical_before = {path: hashlib.sha256(path.read_bytes()).digest() for directory in (root / "wiki", root / "wiki-assets") for path in directory.rglob("*") if path.is_file()}
    expected, base_report = _expected(root)
    expected_paths = set(expected)
    actual = _actual_files(root)
    stale = sorted(actual - expected_paths)
    drifted = sorted(path for path, data in expected.items() if not path.is_file() or path.read_bytes() != data)
    if check:
        if stale:
            raise ValueError(f"stale generated output: {stale[0].relative_to(root)}")
        if drifted:
            raise ValueError(f"generated output differs: {drifted[0].relative_to(root)}")
        return base_report
    for path in drifted:
        _safe_output(path, root)
        if path.exists() and not _is_owned(path, root, previous_manifest):
            raise ValueError(f"unowned output collision: {path.relative_to(root)}")
        _atomic_write(path, expected[path])
    for path in stale:
        _safe_output(path, root)
        if not _is_owned(path, root, previous_manifest):
            raise ValueError(f"unowned stale output: {path.relative_to(root)}")
        path.unlink()
    for directory in sorted((path for root_dir in _owned_roots(root) if root_dir.exists() for path in root_dir.rglob("*") if path.is_dir()), reverse=True):
        try:
            directory.rmdir()
        except OSError:
            pass
    canonical_after = {path: hashlib.sha256(path.read_bytes()).digest() for directory in (root / "wiki", root / "wiki-assets") for path in directory.rglob("*") if path.is_file()}
    if canonical_after != canonical_before:
        raise RuntimeError("canonical producer mirror changed during preparation")
    return PrepareReport(**{**base_report.__dict__, "changed_files": len(drifted) + len(stale)})


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args(argv)
    try:
        report = prepare(args.root, check=args.check)
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"Wiki preparation failed: {exc}", file=sys.stderr)
        return 1
    print(f"Wiki pages: concepts={report.concepts}, entities={report.entities}, sources={report.sources}")
    print(f"Wiki links: references={report.references}")
    print(f"Generated files: {report.generated_files}, changed_files={report.changed_files}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
