#!/usr/bin/env python3
"""Project canonical Overview and compact synthesis into public Hugo pages."""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

GENERATED_NOTICE = "<!-- Generated by scripts/prepare-overview-projections.py; do not edit manually. -->"
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")


@dataclass(frozen=True)
class ProjectionReport:
    synthesis_source: str
    source_count: int
    history_days: int
    changed_files: int


def _split_front_matter(text: str) -> tuple[dict[str, str], str]:
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError("Overview must start with YAML front matter")
    try:
        end = lines.index("---", 1)
    except ValueError as exc:
        raise ValueError("Overview front matter is unterminated") from exc
    metadata: dict[str, str] = {}
    for line in lines[1:end]:
        if not line or line.startswith(" ") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        metadata[key.strip()] = value
    return metadata, "\n".join(lines[end + 1 :])


def _overview_sections(text: str) -> tuple[dict[str, str], str, str, str]:
    metadata, body = _split_front_matter(text)
    patterns = {
        "overview": re.compile(r"(?m)^# Overview\s*$"),
        "synthesis": re.compile(r"(?m)^## Current Synthesis\s*$"),
        "questions": re.compile(r"(?m)^## Open Questions\s*$"),
    }
    matches = {name: list(pattern.finditer(body)) for name, pattern in patterns.items()}
    for name, found in matches.items():
        if len(found) != 1:
            raise ValueError(f"Overview must contain exactly one {name} heading")
    top, synthesis, questions = matches["overview"][0], matches["synthesis"][0], matches["questions"][0]
    if not (top.end() < synthesis.start() < questions.start()):
        raise ValueError("Overview headings are out of order")
    return (
        metadata,
        body[top.end() : synthesis.start()].strip(),
        body[synthesis.end() : questions.start()].strip(),
        body[questions.end() :].strip(),
    )


def _digest_value(value: object) -> str:
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _reject_duplicate_json_keys(pairs: list[tuple[str, object]]) -> dict[str, object]:
    value: dict[str, object] = {}
    for key, item in pairs:
        if key in value:
            raise ValueError(f"duplicate JSON key: {key}")
        value[key] = item
    return value


def _reject_invalid_json_constant(value: str) -> object:
    raise ValueError(f"invalid JSON constant: {value}")


def _load_json_object(path: Path, label: str) -> dict[str, object]:
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"topic synthesis bundle is missing {label}")
    try:
        value = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_reject_duplicate_json_keys,
            parse_constant=_reject_invalid_json_constant,
        )
    except (json.JSONDecodeError, ValueError) as exc:
        raise ValueError(f"topic synthesis bundle has invalid {label}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"topic synthesis bundle {label} must be an object")
    return value


def _render_topic(topic: dict[str, object], claims: dict[str, object], metadata: dict[str, object]) -> str:
    lines = [
        "<!-- Generated by tools.synthesis; do not edit manually. -->",
        "---",
        "generated: true",
        f"topic_id: {topic['topic_id']}",
        f"title: {json.dumps(topic['title'], ensure_ascii=False)}",
        f"last_updated: {metadata['last_updated']}",
        f"as_of_overview_commit: {metadata['as_of_overview_commit']}",
        f"input_digest: {topic['input_digest']}",
        "---",
        "",
        f"# {topic['title']}",
        "",
        "## Current State",
        "",
        str(claims["summary"]).strip(),
        "",
        "## Cross-source Findings",
        "",
    ]
    claim_items = claims["claims"]
    assert isinstance(claim_items, list)
    if not claim_items:
        lines.extend(["No stable cross-source finding has been promoted yet.", ""])
    for claim in claim_items:
        assert isinstance(claim, dict)
        claim_id = str(claim["id"])
        lines.extend([f"### {claim_id.replace('-', ' ').title()}", "", str(claim["statement"]).strip(), ""])
        supports = claim["supporting_wikilinks"]
        assert isinstance(supports, list)
        rendered_supports = ", ".join(f"[[{link}]]" for link in supports)
        if rendered_supports:
            lines.extend([f"**Evidence:** {rendered_supports}", ""])
        qualifications = claim["qualifications"]
        assert isinstance(qualifications, list)
        if qualifications:
            lines.extend(["**Qualifications:**", ""])
            lines.extend(f"- {item}" for item in qualifications)
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _validate_topic_bundle(
    root: Path,
    base: Path,
    manifest: dict[str, object],
    canonical_text: str,
    current_synthesis: str,
    overview_updated: str,
    known_keys: set[str],
) -> None:
    ledger = _load_json_object(base / "paragraph-ledger.json", "paragraph ledger")
    overview_digest = hashlib.sha256(canonical_text.encode("utf-8")).hexdigest()
    if set(ledger) != {"schema_version", "overview_digest", "overview_commit", "paragraphs", "coverage"}:
        raise ValueError("topic synthesis bundle paragraph ledger schema is invalid")
    if ledger.get("schema_version") != 1 or ledger.get("overview_digest") != overview_digest:
        raise ValueError("topic synthesis bundle overview identity is invalid")
    overview_commit = ledger.get("overview_commit")
    if not isinstance(overview_commit, str) or not re.fullmatch(r"[0-9a-f]{40}", overview_commit):
        raise ValueError("topic synthesis bundle overview commit is invalid")
    if manifest.get("overview_commit") != overview_commit:
        raise ValueError("topic synthesis bundle manifest and ledger overview commits differ")

    source_files: set[str] = set()
    source_count = 0
    for source_path in sorted((root / "wiki/sources").glob("*.md")):
        source_meta, _source_body = _split_front_matter(source_path.read_text(encoding="utf-8"))
        if source_meta.get("type") != "source":
            continue
        source_count += 1
        source_files.add(source_meta.get("source_file") or source_path.stem)
    expected_corpus = {"episode_count": len(source_files), "source_count": source_count}
    if manifest.get("corpus") != expected_corpus:
        raise ValueError("topic synthesis bundle corpus differs from canonical sources")

    expected_paragraphs = [item.strip() for item in re.split(r"\n\s*\n", current_synthesis) if item.strip()]
    paragraphs = ledger.get("paragraphs")
    coverage = ledger.get("coverage")
    if not isinstance(paragraphs, list) or len(paragraphs) != len(expected_paragraphs) or not isinstance(coverage, dict):
        raise ValueError("topic synthesis bundle paragraph coverage is invalid")
    paragraph_ids: list[str] = []
    topic_paragraph_ids: dict[str, list[str]] = {}
    for record, expected_text in zip(paragraphs, expected_paragraphs):
        if not isinstance(record, dict) or set(record) != {
            "id", "text", "wikilinks", "primary_topic", "secondary_topics", "topic_scores"
        }:
            raise ValueError("topic synthesis bundle paragraph record is invalid")
        normalized = " ".join(expected_text.split())
        paragraph_id = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        links = sorted(set(WIKILINK_RE.findall(expected_text)))
        if record.get("id") != paragraph_id or record.get("text") != expected_text or record.get("wikilinks") != links:
            raise ValueError("topic synthesis bundle paragraph ledger differs from canonical Overview")
        primary = record.get("primary_topic")
        secondary = record.get("secondary_topics")
        scores = record.get("topic_scores")
        if (
            not isinstance(primary, str)
            or not primary
            or not isinstance(secondary, list)
            or any(not isinstance(item, str) or not item for item in secondary)
            or len(secondary) != len(set(secondary))
            or primary in secondary
            or not isinstance(scores, dict)
            or any(not isinstance(key, str) or not isinstance(value, int) or isinstance(value, bool) or value <= 0 for key, value in scores.items())
        ):
            raise ValueError("topic synthesis bundle topic assignment is invalid")
        paragraph_ids.append(paragraph_id)
        for topic_id in (primary, *secondary):
            topic_paragraph_ids.setdefault(topic_id, []).append(paragraph_id)
    if coverage != {"assigned_paragraph_ids": paragraph_ids, "paragraph_count": len(paragraph_ids)}:
        raise ValueError("topic synthesis bundle does not have exact paragraph ledger coverage")
    if manifest.get("paragraph_count") != len(paragraph_ids):
        raise ValueError("topic synthesis bundle manifest paragraph count is invalid")

    topics = manifest.get("topics")
    if not isinstance(topics, dict) or set(topics) != set(topic_paragraph_ids):
        raise ValueError("topic synthesis bundle topic inventory differs from paragraph coverage")
    expected_inventory = {"current.md", "manifest.json", "paragraph-ledger.json"}
    expected_inventory.update(f"topics/{topic_id}.md" for topic_id in topics)
    expected_inventory.update(f"claims/{topic_id}.json" for topic_id in topics)
    actual_inventory = {
        path.relative_to(base).as_posix()
        for path in base.rglob("*")
        if path.is_file() and not path.is_symlink()
    }
    if actual_inventory != expected_inventory or any(path.is_symlink() for path in base.rglob("*")):
        raise ValueError("topic synthesis bundle file inventory is not exact")

    for topic_id, state in topics.items():
        if not isinstance(topic_id, str) or not isinstance(state, dict) or set(state) != {
            "title", "input_digest", "output_digest", "claim_digest"
        }:
            raise ValueError("topic synthesis bundle manifest topic state is invalid")
        expected_input = _digest_value(topic_paragraph_ids[topic_id])
        if state.get("input_digest") != expected_input or not isinstance(state.get("title"), str):
            raise ValueError("topic synthesis bundle topic input identity is invalid")
        topic_path = base / "topics" / f"{topic_id}.md"
        claims_path = base / "claims" / f"{topic_id}.json"
        if hashlib.sha256(topic_path.read_bytes()).hexdigest() != state.get("output_digest"):
            raise ValueError("topic synthesis bundle topic digest is invalid")
        claims = _load_json_object(claims_path, f"claims/{topic_id}.json")
        if set(claims) != {"topic_id", "summary", "claims"} or claims.get("topic_id") != topic_id:
            raise ValueError("topic synthesis bundle claims identity is invalid")
        if _digest_value(claims) != state.get("claim_digest"):
            raise ValueError("topic synthesis bundle claims digest is invalid")
        if not isinstance(claims.get("summary"), str) or not str(claims["summary"]).strip() or not isinstance(claims.get("claims"), list):
            raise ValueError("topic synthesis bundle claims schema is invalid")
        allowed_links = {
            link
            for record in paragraphs
            if isinstance(record, dict) and record.get("id") in topic_paragraph_ids[topic_id]
            for link in record.get("wikilinks", [])
            if isinstance(link, str)
        }
        claim_records = claims.get("claims")
        assert isinstance(claim_records, list)
        for claim in claim_records:
            if not isinstance(claim, dict) or set(claim) != {
                "id", "status", "statement", "supporting_wikilinks", "qualifications", "global_candidate"
            }:
                raise ValueError("topic synthesis bundle claim schema is invalid")
            supports = claim.get("supporting_wikilinks")
            qualifications = claim.get("qualifications")
            if (
                not isinstance(claim.get("id"), str)
                or not isinstance(claim.get("status"), str)
                or not isinstance(claim.get("statement"), str)
                or not str(claim["statement"]).strip()
                or not isinstance(supports, list)
                or any(not isinstance(link, str) for link in supports)
                or set(supports) - allowed_links
                or set(supports) - known_keys
                or not isinstance(qualifications, list)
                or any(not isinstance(item, str) for item in qualifications)
                or not isinstance(claim.get("global_candidate"), bool)
            ):
                raise ValueError("topic synthesis bundle claim provenance is invalid")
        topic_text = topic_path.read_text(encoding="utf-8")
        topic_meta, _topic_body = _front_matter_after_marker(topic_text, "topic synthesis bundle topic")
        if (
            set(topic_meta) != {"generated", "topic_id", "title", "last_updated", "as_of_overview_commit", "input_digest"}
            or topic_meta.get("generated") is not True
            or topic_meta.get("topic_id") != topic_id
            or topic_meta.get("title") != state["title"]
            or topic_meta.get("input_digest") != expected_input
            or not isinstance(topic_meta.get("as_of_overview_commit"), str)
            or not re.fullmatch(r"[0-9a-f]{40}", str(topic_meta["as_of_overview_commit"]))
        ):
            raise ValueError("topic synthesis bundle topic metadata is invalid")
        try:
            topic_date = dt.date.fromisoformat(str(topic_meta["last_updated"]))
        except ValueError as exc:
            raise ValueError("topic synthesis bundle topic date is invalid") from exc
        if topic_date > dt.date.fromisoformat(overview_updated):
            raise ValueError("topic synthesis bundle topic date exceeds canonical Overview")
        topic = {"topic_id": topic_id, "title": state["title"], "input_digest": expected_input}
        if topic_text != _render_topic(topic, claims, topic_meta):
            raise ValueError("topic synthesis bundle topic Markdown differs from its claims")


def _front_matter_after_marker(text: str, label: str) -> tuple[dict[str, object], str]:
    lines = text.splitlines()
    if not lines or lines[0] != "<!-- Generated by tools.synthesis; do not edit manually. -->":
        raise ValueError(f"{label} is missing its canonical generated marker")
    try:
        start = lines.index("---", 1)
        end = lines.index("---", start + 1)
    except ValueError as exc:
        raise ValueError(f"{label} front matter is invalid") from exc
    metadata: dict[str, object] = {}
    for line in lines[start + 1 : end]:
        if ":" not in line:
            raise ValueError(f"{label} front matter is not canonical")
        key, raw = line.split(":", 1)
        value: object = raw.strip()
        if isinstance(value, str) and len(value) >= 2 and value[0] == value[-1] == '"':
            value = json.loads(value)
        elif value == "true":
            value = True
        elif value == "false":
            value = False
        elif isinstance(value, str) and re.fullmatch(r"0|[1-9][0-9]*", value):
            value = int(value)
        if key.strip() in metadata:
            raise ValueError(f"{label} front matter has a duplicate key")
        metadata[key.strip()] = value
    return metadata, "\n".join(lines[end + 1 :]).strip()


def _compact(
    root: Path,
    known_keys: set[str],
    canonical_text: str,
    current_synthesis: str,
    overview_updated: str,
) -> tuple[dict[str, object], str]:
    base = root / "wiki/_generated/synthesis"
    current = base / "current.md"
    manifest_path = base / "manifest.json"
    if current.is_symlink() or manifest_path.is_symlink() or not current.is_file() or not manifest_path.is_file():
        raise ValueError("compact synthesis current.md and manifest.json are required")
    manifest = _load_json_object(manifest_path, "manifest")
    if not isinstance(manifest, dict) or manifest.get("schema_version") != 1 or manifest.get("generated") is not True:
        raise ValueError("compact synthesis manifest has an unsupported schema")
    if set(manifest) != {
        "schema_version", "generated", "overview_digest", "overview_commit", "content_date",
        "corpus", "paragraph_count", "topics", "global",
    }:
        raise ValueError("topic synthesis bundle manifest schema is invalid")
    if (
        manifest.get("overview_digest") != hashlib.sha256(canonical_text.encode("utf-8")).hexdigest()
        or manifest.get("content_date") != overview_updated
    ):
        raise ValueError("topic synthesis bundle manifest differs from canonical Overview")
    _validate_topic_bundle(
        root, base, manifest, canonical_text, current_synthesis, overview_updated, known_keys
    )
    global_state = manifest.get("global")
    if not isinstance(global_state, dict) or set(global_state) != {
        "candidate_digest", "output_digest", "overview_digest", "overview_commit", "content_date",
        "corpus", "compacted_at", "pending_ingests", "pending_topics",
    }:
        raise ValueError("compact synthesis manifest has invalid global state")
    if (
        global_state.get("overview_digest") != manifest.get("overview_digest")
        or not isinstance(global_state.get("overview_digest"), str)
        or not re.fullmatch(r"[0-9a-f]{64}", str(global_state["overview_digest"]))
        or not isinstance(global_state.get("overview_commit"), str)
        or not re.fullmatch(r"[0-9a-f]{40}", str(global_state["overview_commit"]))
        or not isinstance(global_state.get("pending_ingests"), int)
        or isinstance(global_state.get("pending_ingests"), bool)
        or int(global_state["pending_ingests"]) < 0
        or not isinstance(global_state.get("pending_topics"), list)
    ):
        raise ValueError("compact synthesis global identity is invalid")
    actual_digest = hashlib.sha256(current.read_bytes()).hexdigest()
    if global_state.get("output_digest") != actual_digest:
        raise ValueError("compact synthesis digest differs from its manifest")
    text = current.read_text(encoding="utf-8")
    metadata, body = _front_matter_after_marker(text, "compact synthesis")
    if set(metadata) != {
        "schema_version", "generated", "synthesis_source", "last_updated", "as_of_overview_commit",
        "summary", "episode_count", "source_count", "paragraph_count", "topic_count",
    }:
        raise ValueError("compact synthesis metadata is incomplete")
    if metadata["schema_version"] != 1 or metadata["generated"] is not True or metadata["synthesis_source"] != "compact":
        raise ValueError("compact synthesis source marker is invalid")
    try:
        dt.date.fromisoformat(str(metadata["last_updated"]))
    except ValueError as exc:
        raise ValueError("compact synthesis date is invalid") from exc
    corpus = global_state.get("corpus")
    if (
        not isinstance(corpus, dict)
        or corpus.get("source_count") != metadata["source_count"]
        or corpus.get("episode_count") != metadata["episode_count"]
        or global_state.get("overview_commit") != metadata["as_of_overview_commit"]
        or global_state.get("content_date") != metadata["last_updated"]
    ):
        raise ValueError("compact synthesis source count differs from its manifest")
    topics = manifest.get("topics")
    if not isinstance(topics, dict) or len(topics) != metadata["topic_count"]:
        raise ValueError("compact synthesis topic count differs from its manifest")
    if len(re.findall(r"(?m)^# Current Synthesis\s*$", body)) != 1:
        raise ValueError("compact synthesis must contain one Current Synthesis heading")
    missing = sorted(set(WIKILINK_RE.findall(body)) - known_keys)
    if missing:
        raise ValueError(f"compact synthesis has missing Wiki targets: {', '.join(missing)}")
    return metadata, body


def _page(lines: list[str], body: str) -> bytes:
    return ("\n".join(["---", *lines, "---", "", body.strip(), "", GENERATED_NOTICE]).rstrip() + "\n").encode("utf-8")


def _history_events(root: Path, canonical_text: str, intro: str, updated: str) -> list[tuple[str, str, str]]:
    """Return deterministic visible overview events; first sync is an explicit baseline."""
    del root, canonical_text
    body = intro or "First synchronized canonical overview."
    return [(updated, "first-sync", body)]


def _expected(root: Path) -> tuple[dict[Path, bytes], ProjectionReport]:
    canonical = root / "wiki/overview.md"
    if canonical.is_symlink() or not canonical.is_file():
        raise ValueError("canonical wiki/overview.md is required")
    canonical_text = canonical.read_text(encoding="utf-8")
    overview_meta, intro, canonical_synthesis, questions = _overview_sections(canonical_text)
    updated = overview_meta.get("last_updated", "")
    try:
        dt.date.fromisoformat(updated)
    except ValueError as exc:
        raise ValueError("Overview last_updated is invalid") from exc
    known_keys = {
        path.stem
        for section in ("concepts", "entities", "sources")
        for path in (root / "wiki" / section).glob("*.md")
    }
    compact_meta, compact_body = _compact(
        root, known_keys, canonical_text, canonical_synthesis, updated
    )
    current_lines = [
        'title: "Current Synthesis"', 'type: "wiki"', 'url: "/wiki/current-synthesis/"',
        'outputs: ["html"]', "wiki_projection: true", 'synthesis_source: "compact"',
        f"last_updated: {json.dumps(str(compact_meta['last_updated']))}",
        f"as_of_overview_commit: {json.dumps(str(compact_meta['as_of_overview_commit']))}",
        f"summary: {json.dumps(str(compact_meta['summary']), ensure_ascii=False)}",
        f"source_count: {compact_meta['source_count']}", f"topic_count: {compact_meta['topic_count']}",
    ]
    question_body = "# Open Questions\n\n" + questions
    question_lines = [
        'title: "Open Questions"', 'type: "wiki"', 'url: "/wiki/open-questions/"',
        'outputs: ["html"]', "wiki_projection: true",
    ]
    events = _history_events(root, canonical_text, intro, updated)
    history_lines = [
        'title: "Update History"', 'type: "wiki"', 'url: "/wiki/updates/"',
        'outputs: ["html"]', "wiki_projection: true", f"history_days: {len({event[0] for event in events})}",
    ]
    grouped: dict[str, list[tuple[str, str]]] = {}
    for day, commit, body in events:
        grouped.setdefault(day, []).append((commit, body))
    history_body = ["# Update History", ""]
    for day in sorted(grouped, reverse=True):
        history_body.extend([f"## {day}", ""])
        for commit, body in grouped[day]:
            label = "First synchronized canonical overview" if commit == "first-sync" else f"Canonical overview revision `{commit[:12]}`"
            history_body.extend([f"### {label}", "", body, ""])
    output = root / ".generated/wiki-projections"
    expected = {
        output / "_index.md": _page([
            'title: "Internal Wiki Projections"',
            'type: "wiki"',
            "build:",
            "  render: never",
            "  list: never",
        ], ""),
        output / "current-synthesis.md": _page(current_lines, compact_body),
        output / "open-questions.md": _page(question_lines, question_body),
        output / "update-history/_index.md": _page(history_lines, "\n".join(history_body)),
    }
    return expected, ProjectionReport("compact", int(compact_meta["source_count"]), len(grouped), 0)


def _safe(path: Path, root: Path) -> None:
    output = (root / ".generated/wiki-projections").resolve()
    try:
        (path.parent.resolve() / path.name).relative_to(output)
    except ValueError as exc:
        raise ValueError(f"overview projection escapes owned root: {path}") from exc
    current = root.resolve()
    for part in path.relative_to(root).parts[:-1]:
        current /= part
        if current.exists() and current.is_symlink():
            raise ValueError(f"overview projection ancestor is a symlink: {current}")


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def project(root: Path | str, check: bool = False) -> ProjectionReport:
    root = Path(root).resolve()
    canonical = root / "wiki/overview.md"
    before = hashlib.sha256(canonical.read_bytes()).hexdigest()
    expected, report = _expected(root)
    output = root / ".generated/wiki-projections"
    actual = {path for path in output.rglob("*") if path.is_file()} if output.exists() else set()
    stale = sorted(actual - set(expected))
    drifted = sorted(path for path, data in expected.items() if not path.is_file() or path.read_bytes() != data)
    if check:
        if stale:
            raise ValueError(f"stale overview projection: {stale[0].relative_to(root)}")
        if drifted:
            raise ValueError(f"overview projection differs: {drifted[0].relative_to(root)}")
        return report
    for path in drifted:
        _safe(path, root)
        if path.exists() and GENERATED_NOTICE not in path.read_text(encoding="utf-8", errors="replace"):
            raise ValueError(f"unowned overview projection collision: {path.relative_to(root)}")
        _atomic_write(path, expected[path])
    for path in stale:
        _safe(path, root)
        if GENERATED_NOTICE not in path.read_text(encoding="utf-8", errors="replace"):
            raise ValueError(f"unowned stale overview projection: {path.relative_to(root)}")
        path.unlink()
    for directory in sorted((path for path in output.rglob("*") if path.is_dir()), reverse=True) if output.exists() else []:
        try:
            directory.rmdir()
        except OSError:
            pass
    if hashlib.sha256(canonical.read_bytes()).hexdigest() != before:
        raise RuntimeError("canonical Overview changed during projection")
    return ProjectionReport(report.synthesis_source, report.source_count, report.history_days, len(drifted) + len(stale))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args(argv)
    try:
        report = project(args.root, check=args.check)
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"Overview projection failed: {exc}", file=sys.stderr)
        return 1
    print(f"Overview projections: days={report.history_days}, synthesis={report.synthesis_source}, source_count={report.source_count}, changed_files={report.changed_files}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
